const vogelGeluiden = [
    { naam: "Aalscholver", bestand: "audio/Aalscholver.mp3" },
    { naam: "Appelvink", bestand: "audio/Appelvink.mp3" },
    { naam: "Blauwborst", bestand: "audio/Blauwborst.mp3" },
    { naam: "Blauwe Kiekendief", bestand: "audio/Blauwe Kiekendief.mp3" },
    { naam: "Blauwe Reiger", bestand: "audio/Blauwe Reiger.mp3" },
    { naam: "Boerenzwaluw", bestand: "audio/Boerenzwaluw.mp3" },
    { naam: "Boomklever", bestand: "audio/Boomklever.mp3" },
    { naam: "Boomkruiper", bestand: "audio/Boomkruiper.mp3" },
    { naam: "Boomvalk", bestand: "audio/Boomvalk.mp3" },
    { naam: "Bosrietzanger", bestand: "audio/Bosrietzanger.mp3" },
    { naam: "Bosuil", bestand: "audio/Bosuil.mp3" },
    { naam: "Braamsluiper", bestand: "audio/Braamsluiper.mp3" },
    { naam: "Bruine Kiekendief", bestand: "audio/Bruine Kiekendief.mp3" },
    { naam: "Buizerd", bestand: "audio/Buizerd.mp3" },
    { naam: "Ekster", bestand: "audio/Ekster.mp3" },
    { naam: "Fazant", bestand: "audio/Fazant.mp3" },
    { naam: "Fitis", bestand: "audio/Fitis.mp3" },
    { naam: "Gaai", bestand: "audio/Gaai.mp3" },
    { naam: "Gierzwaluw", bestand: "audio/Gierzwaluw.mp3" },
    { naam: "Goudhaantje", bestand: "audio/Goudhaantje.mp3" },
    { naam: "Goudvink", bestand: "audio/Goudvink.mp3" },
    { naam: "Graspieper", bestand: "audio/Graspieper.mp3" },
    { naam: "Groene Specht", bestand: "audio/Groene Specht.mp3" },
    { naam: "Groenling", bestand: "audio/Groenling.mp3" },
    { naam: "Grote Bonte Specht", bestand: "audio/Grote Bonte Specht.mp3" },
    { naam: "Grote Gele Kwikstaart", bestand: "audio/Grote Gele Kwikstaart.mp3" },
    { naam: "Grutto", bestand: "audio/Grutto.mp3" },
    { naam: "Halsbandparkiet", bestand: "audio/Halsbandparkiet.mp3" },
    { naam: "Havik", bestand: "audio/Havik.mp3" },
    { naam: "Heggemus", bestand: "audio/Heggemus.mp3" },
    { naam: "Holenduif", bestand: "audio/Holenduif.mp3" },
    { naam: "Houtduif", bestand: "audio/Houtduif.mp3" },
    { naam: "Huismus", bestand: "audio/Huismus.mp3" },
    { naam: "IJsvogel", bestand: "audio/IJsvogel.mp3" },
    { naam: "Kauw", bestand: "audio/Kauw.mp3" },
    { naam: "Kerkuil", bestand: "audio/Kerkuil.mp3" },
    { naam: "Kleine Bonte Specht", bestand: "audio/Kleine Bonte Specht.mp3" },
    { naam: "Kleine Karekiet", bestand: "audio/Kleine Karekiet.mp3" },
    { naam: "Kneu", bestand: "audio/Kneu.mp3" },
    { naam: "Koekoek", bestand: "audio/Koekoek.mp3" },
    { naam: "Kokmeeuw", bestand: "audio/Kokmeeuw.mp3" },
    { naam: "Koolmees", bestand: "audio/Koolmees.mp3" },
    { naam: "Kramsvogel", bestand: "audio/Kramsvogel.mp3" },
    { naam: "Krekelzanger", bestand: "audio/Krekelzanger.mp3" },
    { naam: "Kuifeend", bestand: "audio/Kuifeend.mp3" },
    { naam: "Lepelaar", bestand: "audio/Lepelaar.mp3" },
    { naam: "Matkop", bestand: "audio/Matkop.mp3" },
    { naam: "Meerkoet", bestand: "audio/Meerkoet.mp3" },
    { naam: "Merel", bestand: "audio/Merel.mp3" },
    { naam: "Nachtegaal", bestand: "audio/Nachtegaal.mp3" },
    { naam: "Nijlgans", bestand: "audio/Nijlgans.mp3" },
    { naam: "Patrijs", bestand: "audio/Patrijs.mp3" },
    { naam: "Pimpelmees", bestand: "audio/Pimpelmees.mp3" },
    { naam: "Putter", bestand: "audio/Putter.mp3" },
    { naam: "Ransuil", bestand: "audio/Ransuil.mp3" },
    { naam: "Rietzanger", bestand: "audio/Rietzanger.mp3" },
    { naam: "Roek", bestand: "audio/Roek.mp3" },
    { naam: "Roerdomp", bestand: "audio/Roerdomp.mp3" },
    { naam: "Roodborst", bestand: "audio/Roodborst.mp3" },
    { naam: "Roodborsttapuit", bestand: "audio/Roodborsttapuit.mp3" },
    { naam: "Scholekster", bestand: "audio/Scholekster.mp3" },
    { naam: "Slechtvalk", bestand: "audio/Slechtvalk.mp3" },
    { naam: "Snor", bestand: "audio/Snor.mp3" },
    { naam: "Soepeend", bestand: "audio/Soepeend.mp3" },
    { naam: "Sperwer", bestand: "audio/Sperwer.mp3" },
    { naam: "Spotvogel", bestand: "audio/Spotvogel.mp3" },
    { naam: "Spreeuw", bestand: "audio/Spreeuw.mp3" },
    { naam: "Staartmees", bestand: "audio/Staartmees.mp3" },
    { naam: "Stadsduif", bestand: "audio/Stadsduif.mp3" },
    { naam: "Steenuil", bestand: "audio/Steenuil.mp3" },
    { naam: "Tjiftjaf", bestand: "audio/Tjiftjaf.mp3" },
    { naam: "Torenvalk", bestand: "audio/Torenvalk.mp3" },
    { naam: "Tuinfluiter", bestand: "audio/Tuinfluiter.mp3" },
    { naam: "Turkse Tortel", bestand: "audio/Turkse Tortel.mp3" },
    { naam: "Veldleeuwerik", bestand: "audio/Veldleeuwerik.mp3" },
    { naam: "Vink", bestand: "audio/Vink.mp3" },
    { naam: "Waterhoen", bestand: "audio/Waterhoen.mp3" },
    { naam: "Waterral", bestand: "audio/Waterral.mp3" },
    { naam: "Wespendief", bestand: "audio/Wespendief.mp3" },
    { naam: "Wilde Eend", bestand: "audio/Wilde Eend.mp3" },
    { naam: "Winterkoning", bestand: "audio/Winterkoning.mp3" },
    { naam: "Wulp", bestand: "audio/Wulp.mp3" },
    { naam: "Zanglijster", bestand: "audio/Zanglijster.mp3" },
    { naam: "Zilvermeeuw", bestand: "audio/Zilvermeeuw.mp3" },
    { naam: "Zwarte Kraai", bestand: "audio/Zwarte Kraai.mp3" },
    { naam: "Zwarte Wouw", bestand: "audio/Zwarte Wouw.mp3" },
    { naam: "Zwartkop", bestand: "audio/Zwartkop.mp3" }
]